#compilação do projeto

CC=g++
CFLAGS=-c -Wall -g
LDFLAGS=-lpq
OBJS = main.o login.o estoque.o despaxante.o message.o
all: main

main: $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o main -std=c++11

main.o: controller/server.cpp
	$(CC) $(CFLAGS) controller/server.cpp -o main.o

login.o: model/login.cpp
	$(CC) $(CFLAGS) model/login.cpp -o login.o

estoque.o: model/estoque.cpp
	$(CC) $(CFLAGS) model/estoque.cpp -o estoque.o

clean:
	rm -f *.o main

